import { ThemeProvider } from '@/components/theme-provider';
import { Button } from '@/components/ui/button';
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuListItem,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from '@/components/ui/navigation-menu';
import { locales, type Locale } from '@/lib/constants';
import { cn } from '@/lib/utils';
import { Sparkles } from 'lucide-react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import { getDictionary } from './dictionaries';
import './globals.css';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const dict = await getDictionary(params.lang);
  return (
    <html lang={params.lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          enableColorScheme
          disableTransitionOnChange
        >
          <header className="shadow-sm">
            <div className="container mx-auto px-4 py-4 flex items-center justify-between">
              <Link href="/" className="text-2xl font-bold ">
                {dict.company}
              </Link>
              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem>
                    <NavigationMenuTrigger>{dict.nav.tm.title}</NavigationMenuTrigger>
                    <NavigationMenuContent>
                      <ul className="grid gap-3 p-6 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
                        <li className="row-span-3">
                          <NavigationMenuLink asChild>
                            <a
                              className="flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                              href={dict.nav.tm.hero.href}
                            >
                              <Sparkles className={cn('w-6 h-6 text-amber-400')} />
                              <div className="mb-2 mt-4 text-lg font-medium">{dict.nav.tm.hero.title}</div>
                              <p className="text-sm leading-tight text-muted-foreground">
                                {dict.nav.tm.hero.description}
                              </p>
                            </a>
                          </NavigationMenuLink>
                        </li>
                        {dict.nav.tm.items.map((item) => (
                          <NavigationMenuListItem key={item.href} href={item.href} title={item.title}>
                            {item.description}
                          </NavigationMenuListItem>
                        ))}
                      </ul>
                    </NavigationMenuContent>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuTrigger>Programs</NavigationMenuTrigger>
                    <NavigationMenuContent>
                      <ul className="grid w-[400px] gap-3 p-4 md:w-[500px] md:grid-cols-2 lg:w-[600px] ">
                        {dict.nav.programs.map((component) => (
                          <NavigationMenuListItem key={component.title} title={component.title} href={component.href}>
                            {component.description}
                          </NavigationMenuListItem>
                        ))}
                      </ul>
                    </NavigationMenuContent>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <Link href="/about-us" legacyBehavior passHref>
                      <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                        {dict.nav.aboutUs}
                      </NavigationMenuLink>
                    </Link>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <Link href="/contact-us" legacyBehavior passHref>
                      <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                        {dict.nav.contactUs}
                      </NavigationMenuLink>
                    </Link>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
              {/* <ModeToggle  /> */}
              <Button className=" font-semibold">{dict.callToAction}</Button>
            </div>
          </header>
          {children}
          <footer className="bg-emerald-900 text-white py-8">
            <div className="container mx-auto px-4">
              <div className="flex flex-col md:flex-row justify-between items-center">
                <div className="mb-4 md:mb-0">
                  <h3 className="text-2xl font-semibold">{dict.company}</h3>
                  <p className="text-emerald-50">{dict.tagline}</p>
                </div>
                <div className="text-center md:text-right">
                  <p>133 Longueville Rd, Lane Cove NSW 2066</p>
                  <p>
                    Email: <Link href="mailto:tm@northshoremeditation.com">tm@northshoremeditation.com</Link>
                  </p>
                  <p>
                    Phone: <Link href="tel:+61424450578">+61 424 450 578</Link>{' '}
                  </p>
                </div>
              </div>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
